proxy:
    image: jwilder/nginx-proxy
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock
        - ./containers/proxy/proxy.conf:/etc/nginx/conf.d/my_proxy.conf

jorgeben:
    build: "./containers/web/"
    ports:
        - "80"
    environment:
       - VIRTUAL_HOST=webproject.dev.io,*.webproject.dev.io
    volumes:
       - ../:/srv/webproject
    links:
       - database:database.dev.io
       - elasticsearch:elasticsearch.dev.io

database:
    image: mariadb:latest
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - VIRTUAL_HOST=database.dev.io
    volumes:
        - ./tmp/mysql:/var/lib/mysql
        - ./containers/database/my.cnf:/etc/mysql/conf.d/custom.cnf
    ports:
        - "3306:3306"

elasticsearch:
   build: "./containers/elasticsearch"
   environment:
       - VIRTUAL_HOST=elasticsearch.dev.io
   ports:
       - "9200:9500"
   
